# Generated by Django 3.2.6 on 2021-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('tid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Revenue', (('PS', 'Passenger Service'), ('ER', 'Early Return'), ('CM', 'CSO Manning'), ('RSS', 'RS Spare'), ('OPS', 'OPS Spare'))), ('Non Revenue', (('ASA', 'Auto Shunt Allow'), ('MSO', 'Manual Shunt Only'), ('DOWN', 'Down(Not To Move)')))], default='PS', max_length=30)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tid'],
            },
        ),
    ]
